### ISSUE TITLE
Which should the default cast/receive values be, true or false?

### ISSUE THREAD

**Issue by takahirox** [takahirox/KHR_lights_shadows#3]
From: https://twitter.com/mrmaxm/status/1523741146375409664

Currently the `cast/receive` values are `false` by default. Which should the default values be, `true` or `false`?

**Comment by Maksims** [comment]
If no extension is used, most engines will enable shadow cast and receive on by default.
It could be done by having a a file-wide setting of default value, set by this extension. That way parsers can rely on its setting, instead of some rule in a spec of an extension, which can differ from specific engine default behaviour.

**Comment by AdaRoseCannon** [comment]
my gut instinct is `cast:true` `recieve:false` but that's just as a consumer.

**Comment by jbaicoianu** [comment]
I'd vote for defaulting both to `true`.  If a developer is adding a shadow-casting light to the scene, I think they'd be confused to find out that they also need to set cast / receive shadow properties for every object in the scene.  If the scene doesn't have any shadow-casting lights then the flags are no-ops anyway.

**Comment by toji** [comment]
I'd also vote for true in both cases. It feel like the natural, expected behavior in most situations, whereas tuning off shadow casting or receiving is going to primarily be an optimization technique or (rarely) an artistic choice.

**Comment by takahirox** [comment]
Thanks for the feedback, all. I changed the default values to `true` in #5. Please open another issue if anyone thinks the default value should be `false`.
